name: Deploy to Kubernetes

on:
  push:
    branches: [ kubernetes ]
  pull_request:
    branches: [ kubernetes ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_NAME: "customerchurn"    

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t "${DOCKERHUB_USERNAME}/${REPO_NAME}:latest" .  
    - name: Login to DockerHub
      run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
    - name: Push Docker Image to DockerHub
      run: docker push "${DOCKERHUB_USERNAME}/${REPO_NAME}:latest"     #dckr_pat_khXxZp3pnujThU10wGiRMnxMwXY  mkdir ${HOME}/.kube   
    - name: Create kubeconfig
      run: |
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context kubernetes-admin@kubernetes
    - name: Deploy to K8s
      run: kubectl apply -f k8s/
